modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="caerula_arbor"
version="0.5"
displayName="Caerula Arbor"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created using mod maker MCreator, invaluable suggests from Bilibili"
authors="39742, MCreator"
description="From game Arknights"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.caerula_arbor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.caerula_arbor]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.caerula_arbor]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration