modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "caerula_arbor"
version = "${mod_version}"
displayName = "Caerula Arbor"
displayURL = "https://modrinth.com/mod/caerula-arbor"
logoFile = "logo.png"
authors = "${mod_authors}"
description = "${mod_description}"

[[dependencies.caerula_arbor]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.caerula_arbor]]
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "${forge_version_range}" #mandatory
ordering = "NONE"
side = "BOTH"# Here's another dependency

[[dependencies.caerula_arbor]]
modId = "geckolib"
mandatory = true
versionRange = "[4.4.9,)"
ordering = "NONE"
side = "BOTH"