modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="caerula_arbor"
version="0.7.1"
displayName="Caerula Arbor"
displayURL="https://modrinth.com/mod/caerula-arbor"
logoFile="logo.png"
credits="Created using mod maker MCreator, invaluable suggests from Bilibili and QQ"
authors="Apocalypse, MCreator"
description="From game Arknights"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.caerula_arbor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.caerula_arbor]]
    modId="geckolib"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.caerula_arbor]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.caerula_arbor]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration